#!/bin/sh
#find . -iname "*.php" | xargs xgettext --language=PHP --indent --keyword=__ --keyword=_e --keyword=_x:2c,1 --keyword=__ngettext:1,2 --keyword=_n:1,2 -s -n --from-code=UTF-8 -o "lib/core/languages/affiliates.pot"
#find lib/ext -iname "*.php" | xargs xgettext --language=PHP --indent --keyword=__ --keyword=_e --keyword=_x:2c,1 --keyword=__ngettext:1,2 --keyword=_n:1,2 -s -n --from-code=UTF-8 -o "lib/ext/languages/affiliates-pro.pot"
find lib/eext -iname "*.php" | xargs xgettext --language=PHP --indent --keyword=__ --keyword=_e --keyword=_x:2c,1 --keyword=__ngettext:1,2 --keyword=_n:1,2 -s -n --from-code=UTF-8 -o "lib/eext/languages/affiliates-enterprise.pot"
