<?php
class Affiliates_Relations_WordPress extends Affiliates_Relations { public static function view_relations( $affiliate_id ) { global $affiliates_db; $IXAP59 = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; $IXAP68 = isset( $_GET['orderby'] ) ? $_GET['orderby'] : null; $IXAP104 = null; switch ( $IXAP68 ) { case 'from_affiliate_id' : case 'to_affiliate_id' : case 'type' : case 'thru_date' : case 'status' : break; case 'from_affiliate_name' : $IXAP104 = $IXAP68; $IXAP68 = 'fa.name'; break; case 'to_affiliate_name' : $IXAP104 = $IXAP68; $IXAP68 = 'ta.name'; break; case 'from_date' : $IXAP104 = $IXAP68; $IXAP68 = "ar.from_date"; break; default: $IXAP68 = 'from_affiliate_id'; } $IXAP69 = isset( $_GET['order'] ) ? $_GET['order'] : null; switch ( $IXAP69 ) { case 'asc' : case 'ASC' : $switch_order = 'DESC'; break; case 'desc' : case 'DESC' : $switch_order = 'ASC'; break; default: $IXAP69 = 'ASC'; $switch_order = 'DESC'; } $IXAP34 = ''; $IXAP34 .= '<div class="manage-affiliates">' . '<div>' . '<h2>' . __( 'Affiliate Relations', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ) . '</h2>' . '</div>'; $IXAP34 .= '<div class="affiliates-relations-overview">'; $IXAP105 = array( 'from_affiliate_id' => __( 'From Id', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ), 'from_affiliate_name' => __( 'From', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ), 'to_affiliate_id' => __( 'To Id', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ), 'to_affiliate_name' => __( 'To', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ), 'from_date' => __( 'Valid from', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ), ); $IXAP34 .= '
			<table id="" class="wp-list-table widefat fixed" cellspacing="0">
			<thead>
				<tr>
				'; foreach ( $IXAP105 as $key => $IXAP106 ) { $IXAP24 = array( 'orderby' => $key, 'order' => $switch_order ); $IXAP107 = $key; if ( !in_array($key, array( 'edit', 'remove', 'links' ) ) ) { if ( $key == $IXAP68 || $key == $IXAP104 ) { $IXAP108 = strtolower( $IXAP69 ); $IXAP107 = "$key manage-column sorted $IXAP108"; } else { $IXAP107 = "$key manage-column sortable"; } $IXAP106 = '<a href="' . esc_url( add_query_arg( $IXAP24, $IXAP59 ) ) . '"><span>' . $IXAP106 . '</span><span class="sorting-indicator"></span></a>'; } $IXAP34 .= "<th scope='col' class='$IXAP107'>$IXAP106</th>"; } $IXAP34 .= '</tr>
			</thead>
			<tbody>
			'; $affiliates_table = $affiliates_db->get_tablename( "affiliates" ); $affiliates_relations_table = $affiliates_db->get_tablename( "affiliates_relations" ); $IXAP109 = $affiliates_db->get_objects( "SELECT *, fa.name as from_affiliate_name, ta.name as to_affiliate_name FROM $affiliates_relations_table ar
			LEFT JOIN $affiliates_table fa ON from_affiliate_id = fa.affiliate_id
			LEFT JOIN $affiliates_table ta ON to_affiliate_id = ta.affiliate_id
			WHERE from_affiliate_id = %d OR to_affiliate_id = %d
			ORDER BY $IXAP68 $IXAP69", $affiliate_id, $affiliate_id ); if ( !empty( $IXAP109 ) ) { $i = 0; foreach ( $IXAP109 as $IXAP110 ) { $IXAP100 = affiliates_get_affiliate( $IXAP110->from_affiliate_id ); $IXAP111 = affiliates_get_affiliate( $IXAP110->to_affiliate_id ); $IXAP112 = ''; $IXAP113 = ''; $IXAP34 .= '<tr class="' . $IXAP112 . $IXAP113 . ( $i % 2 == 0 ? 'even' : 'odd' ) . '">'; $IXAP34 .= '<td>' . wp_filter_kses( $IXAP110->from_affiliate_id ) . '</td>'; $IXAP34 .= '<td>' . stripslashes( wp_filter_nohtml_kses( $IXAP100['name'] ) ) . '</td>'; $IXAP34 .= '<td>' . wp_filter_kses( $IXAP110->to_affiliate_id ) . '</td>'; $IXAP34 .= '<td>' . stripslashes( wp_filter_nohtml_kses( $IXAP111['name'] ) ) . '</td>'; $IXAP34 .= '<td>' . wp_filter_kses( $IXAP110->from_date ) . '</td>'; $IXAP34 .= '</tr>'; $i++; } } else { $IXAP34 .= '<tr><td colspan="' . count( $IXAP105 ) . '">' . __('There are no results.', AFFILIATES_ENTERPRISE_PLUGIN_DOMAIN ) . '</td></tr>'; } $IXAP34 .= '</tbody>'; $IXAP34 .= '</table>'; $IXAP34 .= '</div>'; $IXAP34 .= '</div>'; echo $IXAP34; } }