<?php
/**
 * Template Name: TEST HOME

 * @since Twenty Twelve 1.0
 */
 
 get_header();


 ?>
<style type="text/css">#menu-primary li{margin-bottom:0px !important;} .op-text-block{background: none !important;}  p, .single-post-content li, #content_area li, .op-popup-button .default-button{font-size:17px;font-family:"Source Sans Pro", sans-serif;color:#444}a, blockquote{font-family:"Source Sans Pro", sans-serif}h1,.main-content h1,.single-post-content h1,.full-width.featured-panel h1,.latest-post .the-title, .step-graphic-style-1-number, .step-graphic-style-2-number, .step-graphic-style-3-number, .step-graphic-style-4-number, .step-graphic-style-5-number{font-family:"Source Sans Pro", sans-serif;color:#D11b69}h2,.main-content h2,.single-post-content h2,.op-page-header h2,.featured-panel h2,.featured-posts .post-content h2,.featured-posts .post-content h2 a,.latest-post h2 a{font-family:"Source Sans Pro", sans-serif;color:#F26724}h3,.main-content h3,.single-post-content h3{font-family:"Source Sans Pro", sans-serif}h4,.main-content h4,.single-post-content h4,.older-post h4 a{font-family:"Source Sans Pro", sans-serif}.site-title,.site-title a{font-family:"Trebuchet MS", Tahoma, sans-serif}a,a:visited{text-decoration:none}a:hover{text-decoration:none}.footer-navigation ul li a{color:#de6f1b;text-decoration:none}.footer-navigation ul li a:hover{color:#50bd27;text-decoration:underline}.footer p{color:#3d3737}.footer h1{color:#3d3737}.footer h2{color:#3d3737}.footer h3{color:#3d3737}.footer h4{color:#3d3737}.footer h5{color:#3d3737}.footer h6{color:#3d3737}.footer a{color:#de6f1b;text-decoration:none}.footer a:hover{color:#50bd27;text-decoration:underline}.footer small.footer-copyright{color:#3d3737}.footer small.footer-copyright a{color:#de6f1b;text-decoration:none}.footer small.footer-copyright a:hover{color:#50bd27;text-decoration:underline}.footer small.footer-disclaimer{color:#3d3737}.footer small.footer-disclaimer a{color:#de6f1b;text-decoration:none}.footer small.footer-disclaimer a:hover{text-decoration:underline;color:#50bd27}</style>
  <div class="container main-content" style="width: 100% !important;">
               
        <div id="content_area" class="">
                    <div class="row one-column cf ui-sortable" id="le_body_row_1" data-style="">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_1_col_1"></div></div></div>
                    <div style="background:#f9f9f9;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #f9f9f9), color-stop(100%, #f9f9f9));background:-webkit-linear-gradient(top, #f9f9f9 0%, #f9f9f9 100%);background:-moz-linear-gradient(top, #f9f9f9 0%, #f9f9f9 100%);background:-ms-linear-gradient(top, #f9f9f9 0%, #f9f9f9 100%);background:-o-linear-gradient(top, #f9f9f9 0%, #f9f9f9 100%);background:linear-gradient(to bottom, #f9f9f9 0%, #f9f9f9 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#f9f9f9, endColorstr=#f9f9f9, GradientType=0);padding-top:30px;padding-bottom:20px;" class="row one-column cf ui-sortable section" id="le_body_row_2" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNmOWY5ZjkiLCJiYWNrZ3JvdW5kQ29sb3JFbmQiOiIjZjlmOWY5IiwicGFkZGluZ1RvcCI6IjMwIiwicGFkZGluZ0JvdHRvbSI6IjIwIiwiYWRkb24iOnsidmlkZW9fYmFja2dyb3VuZF91cmxfbXA0IjoiIiwidmlkZW9fYmFja2dyb3VuZF91cmxfd2VibSI6IiIsInZpZGVvX2JhY2tncm91bmRfdXJsX29ndiI6IiIsInZpZGVvX2JhY2tncm91bmRfb3ZlcmxheV9jb2xvciI6IiIsInZpZGVvX2JhY2tncm91bmRfb3ZlcmxheV9vcGFjaXR5IjoiMCIsInZpZGVvX2JhY2tncm91bmRfb3ZlcmxheV9pbWFnZSI6IiJ9fQ==">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_2_col_1"><div class="element-container cf" data-style="" id="le_body_row_2_col_1_el_1"><div class="element"> <h2 style="font-size:48px;letter-spacing:-2px;text-align:center;line-height:67px;"><span style="color: #f26724;">FREE </span><em><span style="color: #d11b68;">SELF-LOVE</span></em><span style="color: #f26724;"> FESTIVAL</span></h2> </div></div></div></div></div>
                    <div style="padding-top:40px;" class="row five-columns cf ui-sortable section" id="le_body_row_3" data-style="eyJwYWRkaW5nVG9wIjoiNDAiLCJhZGRvbiI6eyJ2aWRlb19iYWNrZ3JvdW5kX3VybF9tcDQiOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX3VybF93ZWJtIjoiIiwidmlkZW9fYmFja2dyb3VuZF91cmxfb2d2IjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2NvbG9yIjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X29wYWNpdHkiOiIwIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2ltYWdlIjoiIn19">
                        <div class="fixed-width"><div class="two-fifths column cols narrow" id="le_body_row_3_col_1"><div class="element-container cf" data-style="" id="le_body_row_3_col_1_el_1"><div class="element"> <div class="op-text-block" style="margin-top:20px;margin-bottom:0px;width:100%;line-height:35px;text-align: left;"><p style="font-size:30px;color:#f26724;letter-spacing:-1px;line-height:35px;text-align: center;">Be part of this <strong>FREE gathering</strong>&nbsp;featuring six&nbsp;<strong>self-love and acceptance luminaries</strong></p>
</div> </div></div><div class="element-container cf hide-mobile hide-tablet" data-style="eyJoaWRlTW9iaWxlIjoxLCJoaWRlVGFibGV0IjoxfQ==" id="le_body_row_3_col_1_el_2"><div class="element">
                <div class="image-caption" style="width:113px;margin-top:0px;margin-bottom:px;margin-right:px;margin-left:px;float: right;"><img alt="" src="<?php  echo get_template_directory_uri(); ?>/images//arrow4.png" class="full-width" border="0" height="55" width="113"></div>
            </div></div></div><div class="one-fifth column cols narrow" id="le_body_row_3_col_2"><div class="element-container cf" data-style="" id="le_body_row_3_col_2_el_1"><div class="element"> 
                <div class="image-caption frame-style-3" style="width:218px;margin-top:0px;margin-bottom:px;margin-right:auto;margin-left:auto;"><div class="frame-style-inner"><img alt="" src="<?php  echo get_template_directory_uri(); ?>/images/carol-p1300.jpg" border="0" height="154" width="154"></div><p class="wp-caption-text">Carol Look</p></div>
             </div></div></div><div class="one-fifth column cols narrow" id="le_body_row_3_col_3"><div class="element-container cf" data-style="" id="le_body_row_3_col_3_el_1"><div class="element"> 
                <div class="image-caption frame-style-3" style="width:218px;margin-top:0px;margin-bottom:px;margin-right:auto;margin-left:auto;"><div class="frame-style-inner"><img alt="" src="<?php  echo get_template_directory_uri(); ?>/images/maiyah200.jpg" class="full-width" border="0" height="154" width="154"></div><p class="wp-caption-text">Maiyah Olivas</p></div>
             </div></div></div><div class="one-fifth column cols narrow" id="le_body_row_3_col_4"><div class="element-container cf" data-style="" id="le_body_row_3_col_4_el_1"><div class="element"> 
                <div class="image-caption frame-style-3" style="width:218px;margin-top:0px;margin-bottom:px;margin-right:auto;margin-left:auto;"><div class="frame-style-inner"><img alt="" src="<?php  echo get_template_directory_uri(); ?>/images/Mel-300-e1446131494976.jpg" class="full-width" border="0" height="154" width="154"></div><p class="wp-caption-text">Melanie Evans</p></div>
             </div></div><div class="element-container cf" data-style="" id="le_body_row_3_col_4_el_2"><div class="element"> <div class="op-text-block" style="margin-top:0px;margin-bottom:0px;width:100%;line-height:35px;text-align: right;"><p style="font-size:20px;font-weight:bold;color:#f26724;line-height:35px;">and many more...</p>
</div> </div></div></div></div></div>
                    <div style="background:#d11b68;padding-top:50px;padding-bottom:40px;border-top-width:1px;border-top-style:solid;border-top-color:#f5f5f5;border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:#f5f5f5;" class="row one-column cf ui-sortable section" id="le_body_row_4" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNkMTFiNjgiLCJwYWRkaW5nVG9wIjoiNTAiLCJwYWRkaW5nQm90dG9tIjoiNDAiLCJib3JkZXJUb3BXaWR0aCI6IjEiLCJib3JkZXJUb3BDb2xvciI6IiNmNWY1ZjUiLCJib3JkZXJCb3R0b21XaWR0aCI6IjEiLCJib3JkZXJCb3R0b21Db2xvciI6IiNmNWY1ZjUiLCJhZGRvbiI6e319">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_4_col_1"><div class="element-container cf" data-style="" id="le_body_row_4_col_1_el_1"><div class="element"> <h2 style="font-size:30px;font-style:normal;font-weight:normal;color:#ffffff;text-align:center;">Experience powerful tools to live your<strong> happiest, most love-filled life</strong> –<br>
from the inside out</h2> </div></div></div></div></div>
                    <div class="row two-columns cf ui-sortable" id="le_body_row_5" data-style="">
                        <div class="fixed-width"><div class="one-half column cols" id="le_body_row_5_col_1"><div class="element-container cf" data-style="" id="le_body_row_5_col_1_el_1"><div class="element"> <div class="video-plugin-new not-flowplayer" style="max-width:100%; width:460px; height:auto; padding-top:0; padding-bottom:0; margin:0 auto;margin:0 auto; border: 0px solid #fff;margin-bottom: 20px;"><div style="width:460px;height:0;  padding-bottom: 56.304347826087%; padding-top:0;"><!--iframe src="<?php  echo get_template_directory_uri(); ?>/images/6e1hly4txu.htm" allowtransparency="true" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" oallowfullscreen="oallowfullscreen" msallowfullscreen="msallowfullscreen" height="259" frameborder="0" width="460"></iframe--><video width="320" height="240" controls>
  <source src="<?php echo get_template_directory_uri() ?>/images/file.mp4" type="video/mp4">
 Your browser does not support the video tag.
</video><script src="<?php  echo get_template_directory_uri(); ?>/images/E-v1.js" async=""></script></div></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_5_col_1_el_2"><div class="element"> <div style="height:20px"></div> </div></div></div><div class="one-half column cols" id="le_body_row_5_col_2"><div class="element-container cf" data-style="" id="le_body_row_5_col_2_el_1"><div class="element"> <div style="height:15px"></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_5_col_2_el_2"><div class="element"> <h2 style="color:#ffa600;text-align:center;">Join this<br>
FREE summit!</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_5_col_2_el_3"><div class="element"> <div class="op-text-block" style="width:370px;line-height:22px;margin: 0 auto;text-align:center;"><p style="font-size:18px;line-height:22px;text-align: center;">Enter your first name and email address to join our&nbsp;FREE ONLINE Summit and<br>
<span style="color: 41a4d1;"><strong>claim your bonus gift</strong></span></p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_5_col_2_el_4"><div class="element"> <div style="height:20px"></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_5_col_2_el_5"><div class="element"> <div class="op-popup cf" data-width="700" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442169878147"><div class="op-popup-button "><div style="text-align:center"><style type="text/css">#btn_1_905e1491036df309825580ee786c618c .text {font-size:25px;color:#ffffff;font-weight:bold;text-shadow:#ffbb00 0px 1px 0px;}#btn_1_905e1491036df309825580ee786c618c .subtext {text-shadow:#ffbb00 0px 1px 0px;}#btn_1_905e1491036df309825580ee786c618c {padding:21px 16px;border-color:#000000;border-width:0px;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;background:#ffa600;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffa600), color-stop(100%, #ffa435));background:-webkit-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-moz-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-ms-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-o-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:linear-gradient(to bottom, #ffa600 0%, #ffa435 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffa600, endColorstr=#ffa435, GradientType=0);box-shadow:none;}#btn_1_905e1491036df309825580ee786c618c .gradient {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_905e1491036df309825580ee786c618c .shine {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_905e1491036df309825580ee786c618c .active {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_905e1491036df309825580ee786c618c .hover {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}</style><a href="" id="btn_1_905e1491036df309825580ee786c618c" class="css-button style-1"><span class="text">Yes, please include me!</span><span class="hover"></span><span class="active"></span></a></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:30px;font-weight:bold;color:#ffa600;">Register For Our Free Summit</p>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:18px;font-style:normal;font-weight:300;color:#212121;">Enter your first name and email to join out FREE Summit&nbsp;and claim your complimentary bonus gifts.</p>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true">
<div id="58d26e5db0f43" class="optin-box optin-box-6" style="margin-right: auto;margin-left: auto;">
    <div class="optin-box-content">
        <form action="https://forms.ontraport.com/v2.4/form_processor.php?" method="post" class="cf op-optin-validation"><div style="display:none"><input name="submit-button" value="" type="hidden"><input name="afft_" value="" type="hidden"><input name="aff_" value="" type="hidden"><input name="sess_" value="" type="hidden"><input name="ref_" value="" type="hidden"><input name="own_" value="" type="hidden"><input name="oprid" value="" type="hidden"><input name="contact_id" value="" type="hidden"><input name="utm_source" value="" type="hidden"><input name="utm_medium" value="" type="hidden"><input name="utm_term" value="" type="hidden"><input name="utm_content" value="" type="hidden"><input name="utm_campaign" value="" type="hidden"><input name="referral_page" value="" type="hidden"><input name="uid" value="p2c11452f184" type="hidden"><input name="redirect_url" value="https://forms.ontraport.com/v2.4/form_processor.php?" type="hidden"><input name="email_field" value="email" type="hidden"></div>            <div class="text-boxes">
          <div class="text-box name"><input required="required" name="firstname" placeholder="Enter your first name" type="text"></div><div class="text-box email"><input required="required" name="email" placeholder="Enter your email address" type="email"></div>            </div>
            <input id="op_optin_nonce" name="op_optin_nonce" value="9af5157843" type="hidden"><input name="_wp_http_referer" value="/" type="hidden">            <div style="text-align:center"><style type="text/css">#btn_1_762fdfff51297e5242d85f72e1f207da .text {font-size:25px;color:#ffffff;font-weight:bold;text-shadow:#ffa600 0px 1px 0px;}#btn_1_762fdfff51297e5242d85f72e1f207da .subtext {text-shadow:#ffa600 0px 1px 0px;}#btn_1_762fdfff51297e5242d85f72e1f207da {padding:21px 21px;border-color:#000000;border-width:0px;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;background:#ffa600;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffa600), color-stop(100%, #ffa435));background:-webkit-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-moz-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-ms-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-o-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:linear-gradient(to bottom, #ffa600 0%, #ffa435 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffa600, endColorstr=#ffa435, GradientType=0);box-shadow:none;}#btn_1_762fdfff51297e5242d85f72e1f207da .gradient {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .shine {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .active {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .hover {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}</style><button type="submit" id="btn_1_762fdfff51297e5242d85f72e1f207da" class="css-button style-1 location_optin_box_style_7"><span class="text">Yes, I want in!</span><span class="hover"></span><span class="active"></span></button></div>                    </form>
    <p class="privacy"><img src="<?php  echo get_template_directory_uri(); ?>/images/privacy.png" alt="privacy" height="15" width="16"> We value your privacy and would never spam you</p>    </div>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:300;color:#212121;">You will also receive our free e-news.<br>
<strong>Your info will never be shared or sold. Ever.</strong></p>
</div></div></div></div> </div></div></div></div></div>
                    <div style="background:#d11b68;padding-top:40px;padding-bottom:30px;border-top-width:px;border-top-style:solid;border-top-color:;border-bottom-width:px;border-bottom-style:solid;border-bottom-color:;" class="row one-column cf ui-sortable section" id="le_body_row_6" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNkMTFiNjgiLCJwYWRkaW5nVG9wIjoiNDAiLCJwYWRkaW5nQm90dG9tIjoiMzAiLCJib3JkZXJUb3BXaWR0aCI6IiIsImJvcmRlclRvcENvbG9yIjoiIiwiYm9yZGVyQm90dG9tV2lkdGgiOiIiLCJib3JkZXJCb3R0b21Db2xvciI6IiIsImFkZG9uIjp7fX0=">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_6_col_1"><div class="element-container cf" data-style="" id="le_body_row_6_col_1_el_1"><div class="element"> <h2 style="font-size:27px;font-style:normal;font-weight:normal;color:#ffffff;text-align:center;">Learn
 from six experts and luminaries from across the fields of self-love, 
energy healing, and life-coaching about how to love and accept yourself 
for who you are right now</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_6_col_1_el_2"><div class="element"> <div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:22px;font-style:italic;color:#ffffff;">(click on speaker's photo to see bio)</p>
</div> </div></div></div></div></div>
                    <div class="row four-columns cf ui-sortable" id="le_body_row_7" data-style="">
                        <div class="fixed-width"><div class="one-fourth column cols narrow" id="le_body_row_7_col_1"><div class="element-container cf frame-style-inner" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIifQ==" id="le_body_row_7_col_1_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442240890831"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/Mel-300-e1446131494976.jpg" alt="" height="200" width="200"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><strong><img class="size-medium wp-image-2248 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/Mel-headshot.jpg" alt="Mel headshot" srcset="https://i1.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/09/Mel-headshot.jpg?resize=269%2C300 269w, https://i1.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/09/Mel-headshot.jpg?w=862 862w" sizes="(max-width: 269px) 100vw, 269px" height="300" width="269">Melanie Evans<br>
</strong></p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><span>Melanie
 Tonia Evans is a Narcissistic Abuse Recovery Expert, healer, author and
 radio host. Melanie is the creator of the healing system called Quanta 
Freedom Healing and the Narcissistic Abuse Recovery Program.</span></p>
</div></div></div></div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_1_el_2"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:20px;margin: 0 auto;text-align:center;padding-top:5px;padding-bottom:5px;"><p style="font-size:17px;font-weight:bold;line-height:20px;">Melanie Evans</p>
</div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_1_el_3"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:16px;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:normal;line-height:16px;">Narcissistic Abuse</p>
</div></div></div></div><div class="one-fourth column cols narrow" id="le_body_row_7_col_2"><div class="element-container cf frame-style-inner" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIifQ==" id="le_body_row_7_col_2_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442249185955"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/maiyah200.jpg" alt="" height="200" width="200"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><strong><img class="size-full wp-image-2069 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/Maiyah.htm" alt="Maiyah" data-recalc-dims="1">Maiyah Olivas</strong></p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">A
 healer with over 30 years of experience and advanced training in over 
30 modalities, Maiyah Olivas holds the rank of Third Degree Black Belt 
and Certified Advanced Therapeutic Qi Gong Instructor. Known as “the 
Queen of Age Reversal,” and “the Ninja of Transmutation” she’s worked 
with over 3000 people to improve their emotional, financial and physical
 situations, often instantaneously! She loves synthesizing new 
techniques with ancient secrets to create miracles on a daily basis such
 as: shrinking tumors, reversing diabetes, reviving necrotic tissue and 
ending decades-long back pain and migraines. When not working with 
private clients, developing problem-solving products or teaching 
cutting-edge classes, Maiyah can be found working with at-risk youth in 
her local afterschool program, teaching ukulele and keyboard.</p>
</div></div></div></div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_2_el_2"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:20px;margin: 0 auto;text-align:center;padding-top:5px;padding-bottom:5px;"><p style="font-size:17px;font-weight:bold;line-height:20px;">Maiyah Olivas</p>
</div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_2_el_3"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:16px;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:normal;line-height:16px;">Living Your Life Purpose</p>
</div></div></div></div><div class="one-fourth column cols narrow" id="le_body_row_7_col_3"><div class="element-container cf frame-style-inner" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIifQ==" id="le_body_row_7_col_3_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442252106029"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/Mia-200.jpg" alt="" height="200" width="200"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><strong><img class="size-full wp-image-2230 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/Mia1-1.htm" alt="Mia" data-recalc-dims="1">Mia Den Haan<br>
</strong></p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">As
 an internationally known Spiritual Healer and Channel for Spirit, Mia 
receives information directly from your Soul’s highest level of wisdom. 
She can receive guidance for any issues, personal or family matters or 
business. She receives information about your body and mental, emotional
 and spiritual planes, karmic issues or your genetic lineage.</p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">With
 her gift Mia has helped many, including young children improve any 
aspect, such as improve physical, mental and emotional wellbeing, 
improve cognition with young children, more harmonious relationships, 
work issues, purpose in life and development of spiritual gifts.</p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">On
 occasion she will receive predictions such as the ones about the 
weather which were documented in an earlier published book she authored.</p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">Mia
 is also a certified Life and Business Coach with many years of 
practical business experience as a business owner an employer since 
1990. As a healer she trained as a Reiki Master, Seichim Healer, Zenna 
Healer and Reconnective Healing and Shell essence and several flower 
essence ranges.</p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">She
 received this special Healing method, called Your Divine Soul Essence™,
 in 2002 through her ability to channel Spirit. She has since used this 
method, which includes both your Soul Essence and Spirit, as the main 
modality in her healing practice.</p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">Mia’s
 gift is that she hears directly from your highest Soul level what lies 
at the core of any issue and will, with help of her healing gift, clear 
this at all levels of being.</p>
</div></div></div></div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_3_el_2"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:20px;margin: 0 auto;text-align:center;padding-top:5px;padding-bottom:5px;"><p style="font-size:17px;font-weight:bold;line-height:20px;">Mia Den Haan</p>
</div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_3_el_3"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:16px;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:normal;line-height:16px;">Love</p>
</div></div></div></div><div class="one-fourth column cols narrow" id="le_body_row_7_col_4"><div class="element-container cf frame-style-inner" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIifQ==" id="le_body_row_7_col_4_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442249302266"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/carol-p1300.jpg" alt="" height="200" width="200"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><strong><img class="size-full wp-image-1845 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/carol-p1.jpg" alt="carol-p1" height="266" width="200">Carol Look</strong></p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;">EFT
 Master Carol Look has been a pioneer and leading voice in the EFT 
community for 17 years. Before becoming an EFT Master, Carol was trained
 as a Clinical Social Worker and earned her Doctoral Degree in Clinical 
Hypnotherapy. Carol is recognized and respected around the globe as a 
premier success and abundance coach, inspiring people to attract 
abundance into their lives by using EFT and the Law of Attraction to 
clear limiting beliefs and build prosperity consciousness.</p>
</div></div></div></div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_4_el_2"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:20px;margin: 0 auto;text-align:center;padding-top:5px;padding-bottom:5px;"><p style="font-size:17px;font-weight:bold;line-height:20px;">Carol Look</p>
</div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_7_col_4_el_3"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:16px;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:normal;line-height:16px;">Self-Confidence</p>
</div></div></div></div></div></div>
                    <div class="row two-columns cf ui-sortable" id="le_body_row_8" data-style="">
                        <div class="fixed-width"><div class="one-half column cols" id="le_body_row_8_col_1"><div class="element-container cf frame-style-inner" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIifQ==" id="le_body_row_8_col_1_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442241472809"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/Lyon-Zonamyari.jpg" alt="" height="200" width="200"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><span><img class="size-full wp-image-4546 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/Lyon-Zonamyari-1.jpg" alt="Lyon-Zonamyari" srcset="https://i0.wp.com/lovemyselflovemylife.com/wp-content/uploads/2016/01/Lyon-Zonamyari-1.jpg?w=200 200w, https://i0.wp.com/lovemyselflovemylife.com/wp-content/uploads/2016/01/Lyon-Zonamyari-1.jpg?resize=150%2C150 150w" sizes="(max-width: 200px) 100vw, 200px" height="200" width="200"><strong>Lyon Zonamyari<br>
</strong> Name Reality is a result of the author’s personal quest in 
search for answers. At an early age Lyon quickly discovered that 
conforming with conventional was not his path and questioned our very 
existence when just eight years old. A massive spiritual growth period 
over twenty years guided by no less than three mentors all at Oracle 
level took him beyond the physical frequencies of this planet. However, 
despite all this, his personal life continued a roller coaster pattern 
of turbulent trials and tribulations until he discovered an ancient 
knowledge that changed his life forever.</span></p>
</div></div></div></div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_8_col_1_el_2"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:20px;margin: 0 auto;text-align:center;padding-top:5px;padding-bottom:5px;"><p style="font-size:17px;font-weight:bold;line-height:20px;">Lyon Zonamyari</p>
</div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_8_col_1_el_3"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:16px;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:normal;line-height:16px;">Name Reality</p>
</div></div></div></div><div class="one-half column cols" id="le_body_row_8_col_2"><div class="element-container cf frame-style-inner" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIifQ==" id="le_body_row_8_col_2_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442241472809"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/jeff200x200.jpg" alt="" height="200" width="200"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><strong><img class="alignleft wp-image-3990 size-full" src="<?php  echo get_template_directory_uri(); ?>/images/jeff-square-new.jpg" alt="" srcset="https://i2.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/10/jeff-square-new.jpg?w=200 200w, https://i2.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/10/jeff-square-new.jpg?resize=150%2C150 150w" sizes="(max-width: 200px) 100vw, 200px" height="200" width="200">Jeffrey Gignac<br>
</strong></p>
<p style="font-size:15px;font-style:normal;font-weight:300;color:#212121;"><span>Growing
 up in small town Canada, the son of a Psychologist and Social Worker, 
Jeff has always displayed a passion for helping others. He was one of 
the youngest people in North America to be certified as a practitioner 
of Neuro-Linguistic Programming at the age of 15. He studied psychology 
and at the University of Windsor before becoming is a clinical 
hypnotherapist and a World Renowned expert in the neuroscience of 
brainwave stimulation. Jeffrey is published author, writing his first 
book in 1999 "The Enzyme Revolution"with his most recent contribution, 
“The Secret Skill” appearing in “Adventures in Manifesting” Success and 
Spirituality. </span></p>
</div></div></div></div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_8_col_2_el_2"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:20px;margin: 0 auto;text-align:center;padding-top:5px;padding-bottom:5px;"><p style="font-size:17px;font-weight:bold;line-height:20px;">Jeffrey Gignac</p>
</div></div></div><div class="element-container cf" data-style="e30=" id="le_body_row_8_col_2_el_3"><div class="element"><div class="op-text-block" style="margin-bottom:22px;width:100%;line-height:16px;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:normal;line-height:16px;">Brain</p>
</div></div></div></div></div></div>
                    <div class="row three-columns cf ui-sortable" id="le_body_row_9" data-style="">
                        <div class="fixed-width"><div class="one-third column cols narrow" id="le_body_row_9_col_1"></div><div class="one-third column cols narrow" id="le_body_row_9_col_2"></div><div class="one-third column cols narrow" id="le_body_row_9_col_3"></div></div></div>
                    <div style="background:#f26724;padding-top:40px;padding-bottom:30px;border-top-width:px;border-top-style:solid;border-top-color:;border-bottom-width:px;border-bottom-style:solid;border-bottom-color:;" class="row one-column cf ui-sortable section" id="le_body_row_10" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNmMjY3MjQiLCJwYWRkaW5nVG9wIjoiNDAiLCJwYWRkaW5nQm90dG9tIjoiMzAiLCJib3JkZXJUb3BXaWR0aCI6IiIsImJvcmRlclRvcENvbG9yIjoiIiwiYm9yZGVyQm90dG9tV2lkdGgiOiIiLCJib3JkZXJCb3R0b21Db2xvciI6IiIsImFkZG9uIjp7fX0=">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_10_col_1"><div class="element-container cf" data-style="" id="le_body_row_10_col_1_el_1"><div class="element"> <h2 style="font-size:45px;font-style:normal;font-weight:300;color:#ffffff;text-align:center;"><strong>Here's what people are saying </strong>from past years of the Love Myself Love My Life event<strong><em><br>
</em></strong></h2> </div></div></div></div></div>
                    <div class="row two-columns cf ui-sortable" id="le_body_row_11" data-style="">
                        <div class="fixed-width"><div class="one-half column cols" id="le_body_row_11_col_1"><div class="element-container cf" data-style="" id="le_body_row_11_col_1_el_1"><div class="element"> 
<div id="46a7d8b35e57b103f2beb8784df7c80a" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>what makes yours different, is that it is REAL and down to earth and attainable</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>Where do I
 begin to tell you how much it has meant to me personally to be able to 
participate in your webinar series. Thank you so much for all of your 
efforts to offer life changing information to help all of us women 
accept ourselves just as we are and go for our dreams. There are lots of
 women out in the world now who are doing their own version of making 
the world a better place. In my eyes, what makes yours different, is 
that it is REAL and down to earth and attainable, even practical yet 
unique information. Thank you so very much for your awesome 
contribution.</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>&nbsp; – <cite>Dianne</cite>,&nbsp;<cite>California</cite></em></p>
</div>
</div></div>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_11_col_1_el_2"><div class="element"> 
<div id="f9a1b9fcfa397fbfa7dda8984223ce5e" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>I’ve been so incredibly impressed with the diversity and quality of the speakers</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>I just 
wanted to say THANK YOU for setting these amazing talks up. I have 
emailed family and friends, so that they too can benefit. I just wanted 
to let you know that I’ve been so incredibly impressed with the 
diversity and quality of the speakers. This is really wonderful and I 
hope to get a chance to listen to your next one too!</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>- <cite>Isobel, California</cite></em></p>
</div>
</div></div>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_11_col_1_el_3"><div class="element"> 
<div id="bff08808ecd2b3700966dd51b25b3788" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>looked forward to each and every interview&nbsp;</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>This was a
 wonderful summit! It covered so many different aspects of our lives, 
and had a lot of useful information. I really liked it, and actually 
looked forward to each and every interview (something I’ve never done in
 any other summit). Thanks for putting this together!</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>-&nbsp;<cite>Megha, California</cite></em></p>
</div>
</div></div>
</div> </div></div></div><div class="one-half column cols" id="le_body_row_11_col_2"><div class="element-container cf" data-style="" id="le_body_row_11_col_2_el_1"><div class="element"> 
<div id="9c0e6d13dbae89be3319ac1055f685c1" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>&nbsp;I have recently healed at the very deepest levels thanks to these amazing calls</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>Dear 
Aimee - You have had a tremendous impact on my life! Your gift of 
healing and the guests you invite to your shows are totally amazing! 
Your gifts are beyond description. I can't even begin to list the 
awesome results and miraculous changes I've experienced as a result of 
this magnificent energy.<br>
After incurring tremendous debt by working with therapists for PTSD, I 
have recently healed at the very deepest levels thanks to these amazing 
calls and the healers you interview. You're all incredibly gifted and so
 gracious and generous in sharing. Since emotion transcends words and 
language, I hope you can feel how thankful I am to you all! May you be 
blessed in every aspect of life.</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;">- CHD, Los Angeles, California</p>
</div>
</div></div>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_11_col_2_el_2"><div class="element"> 
<div id="fd5a7dac26539c6719778d421e0a4c0c" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>I have really upped the quality of my life</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>You are 
such an inspiration to me!!! I have really upped the quality of my life 
because of all the resources that I have received from you. My heart 
felt gratitude to you for all that you are doing. I deeply appreciate 
it.</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>-&nbsp;<cite>Su, Virginia</cite></em></p>
</div>
</div></div>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_11_col_2_el_3"><div class="element"> 
<div id="5d2d0845de45333c73d34d59e93d6688" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>&nbsp;I’ve been searching for answers for a long time</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>I’m so 
glad for your teleseminars … they’ve been eye opening and so very 
helpful. I’ve been searching for answers for a long time … years … and I
 finally feel like I’m heading in a better direction!</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>-&nbsp;<cite>Angelique, Florida</cite></em></p>
</div>
</div></div>
</div> </div></div></div></div></div>
                    <div class="row one-column cf ui-sortable" id="le_body_row_12" data-style="">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_12_col_1"></div></div></div>
                    <div style="background:#f26724;padding-top:40px;padding-bottom:30px;border-top-width:px;border-top-style:solid;border-top-color:;border-bottom-width:px;border-bottom-style:solid;border-bottom-color:;" class="row one-column cf ui-sortable section" id="le_body_row_13" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNmMjY3MjQiLCJwYWRkaW5nVG9wIjoiNDAiLCJwYWRkaW5nQm90dG9tIjoiMzAiLCJib3JkZXJUb3BXaWR0aCI6IiIsImJvcmRlclRvcENvbG9yIjoiIiwiYm9yZGVyQm90dG9tV2lkdGgiOiIiLCJib3JkZXJCb3R0b21Db2xvciI6IiIsImFkZG9uIjp7fX0=">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_13_col_1"><div class="element-container cf" data-style="" id="le_body_row_13_col_1_el_1"><div class="element"> <h2 style="font-size:45px;font-style:normal;font-weight:300;color:#ffffff;text-align:center;">Reserve Your Spot Today And Receive the book<br>
<em><strong>Loving All of Me -<br>
Even the Parts I Thought I Had to Hate</strong></em></h2> </div></div></div></div></div>
                    <div style="background:#f0f0f0;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #f0f0f0), color-stop(100%, #f0f0f0));background:-webkit-linear-gradient(top, #f0f0f0 0%, #f0f0f0 100%);background:-moz-linear-gradient(top, #f0f0f0 0%, #f0f0f0 100%);background:-ms-linear-gradient(top, #f0f0f0 0%, #f0f0f0 100%);background:-o-linear-gradient(top, #f0f0f0 0%, #f0f0f0 100%);background:linear-gradient(to bottom, #f0f0f0 0%, #f0f0f0 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#f0f0f0, endColorstr=#f0f0f0, GradientType=0);" class="row three-columns cf ui-sortable section" id="le_body_row_14" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNmMGYwZjAiLCJiYWNrZ3JvdW5kQ29sb3JFbmQiOiIjZjBmMGYwIiwiYWRkb24iOnsidmlkZW9fYmFja2dyb3VuZF91cmxfbXA0IjoiIiwidmlkZW9fYmFja2dyb3VuZF91cmxfd2VibSI6IiIsInZpZGVvX2JhY2tncm91bmRfdXJsX29ndiI6IiIsInZpZGVvX2JhY2tncm91bmRfb3ZlcmxheV9jb2xvciI6IiIsInZpZGVvX2JhY2tncm91bmRfb3ZlcmxheV9vcGFjaXR5IjoiMCIsInZpZGVvX2JhY2tncm91bmRfb3ZlcmxheV9pbWFnZSI6IiJ9fQ==">
                        <div class="fixed-width"><div class="two-thirds column cols" id="le_body_row_14_col_1"><div class="element-container cf" data-style="" id="le_body_row_14_col_1_el_1"><div class="element"> <div class="op-text-block" style="margin-bottom:5px;width:100%;line-height:28px;text-align: left;padding-bottom:0px;"><p style="font-size:28px;color:#41a4d1;line-height:28px;"><strong>from your host Aimee Serafini<br>
</strong></p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_14_col_1_el_2"><div class="element"> <div style="height:30px"></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_14_col_1_el_3"><div class="element"> <div class="op-text-block" style="margin-bottom:0px;width:100%;text-align: left;padding-bottom:0px;"><div class="element-container cf" data-style="" id="le_body_row_4_col_2_el_2">
<div class="element">
<ul class="bullet-list 1">
<li style="font-size:18px;">How often do you <mark>hear thoughts like I'm not good enough in your head</mark>?</li>
<li style="font-size:18px;">How often do you <mark>judge yourself against others</mark> and find yourself lacking?</li>
<li style="font-size:18px;">Do you feel like you <mark>let yourself down</mark>?</li>
</ul>
</div>
</div>
<div class="element-container cf" data-style="" id="le_body_row_4_col_2_el_3">
<div class="element">
<div class="op-text-block">
<p style="font-size:18px;">It’s time to re-train that voice in our head 
from being our Own Worst Critic to our Own Best Friend. Someone who 
encourages and supports us instead of browbeats and criticizes us. In 
this book, you will learn a simple, fun technique to start the process. 
It only takes a few minutes a day.</p>
</div>
</div>
</div>
</div> </div></div></div><div class="one-third column cols narrow" id="le_body_row_14_col_2"><div class="element-container cf frame-style-inner1" data-style="eyJhZHZhbmNlZENsYXNzIjoiZnJhbWUtc3R5bGUtaW5uZXIxIn0=" id="le_body_row_14_col_2_el_1"><div class="element"><div class="op-popup cf" data-width="750" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442157102687"><div class="op-popup-button "><div style="text-align:center"><button type="submit" class="image-button"><img src="<?php  echo get_template_directory_uri(); ?>/images/Aimee-Serafini-headshot-555x779-1.jpg" alt="" height="300" width="214"></button></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:15px;color:#212121;"><strong><a href="https://i1.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/09/Aimee-Serafini-headshot-555x779-1.jpg"><img class="alignleft size-medium wp-image-2119" src="<?php  echo get_template_directory_uri(); ?>/images/Aimee-Serafini-headshot-555x779-1.jpg" alt="Aimee Serafini headshot 555x779" srcset="https://i1.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/09/Aimee-Serafini-headshot-555x779-1.jpg?resize=214%2C300 214w, https://i1.wp.com/lovemyselflovemylife.com/wp-content/uploads/2015/09/Aimee-Serafini-headshot-555x779-1.jpg?w=555 555w" sizes="(max-width: 214px) 100vw, 214px" height="300" width="214"></a>Your Host Aimee Serafini<br>
</strong> Aimee Serafini is a women’s empowerment coach and an energy 
psychology practitioner specializing in helping women empower themselves
 to go for their dreams by loving and accepting themselves exactly as 
they are right now. &nbsp;She is the creator of the annual self-love 
event&nbsp;<em>Love Myself Love My Life&nbsp;</em>and the annual event&nbsp;<em>Loving Food Loving Life </em>empowering women to explore and heal from emotional eating</p>
<p style="font-size:15px;color:#212121;">Prior to finding her life’s 
calling as a coach in 2002, Aimee considered herself a “traveler”. After
 deciding at the age of 15 that she wanted to see the world, she 
structured her life around travel, moving around both coasts of the 
United States to save money to fund further travel.&nbsp; She has 
backpacked through over 50 countries on her own, logging over 5 years on
 the road, in addition to living in Bangkok and New Zealand. Although 
she still loves to travel and incorporates it in her life, she is now 
most passionate about coaching women to love and accept themselves 
exactly as the are and let go of judgments and comparisons so they feel 
worthy enough to reach for their dreams.</p>
</div></div></div></div></div></div></div></div></div>
                    <div style="padding-top:90px;padding-bottom:20px;" class="row two-columns cf ui-sortable" id="le_body_row_15" data-style="eyJwYWRkaW5nVG9wIjoiOTAiLCJwYWRkaW5nQm90dG9tIjoiMjAiLCJhZGRvbiI6e319">
                        <div class="fixed-width"><div class="one-half column cols" id="le_body_row_15_col_1"><div class="element-container cf" data-style="" id="le_body_row_15_col_1_el_1"><div class="element"> <h2 style="color:#ffa600;text-align:center;">Register for FREE and claim your special BONUS GIFT!</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_15_col_1_el_2"><div class="element"> <div style="height:10px"></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_15_col_1_el_3"><div class="element"> <div style="height:10px"></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_15_col_1_el_4"><div class="element"> <div style="height:10px"></div> </div></div><div class="split-half column cols subcol" id="le_body_row_15_col_100"><div class="element-container cf hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet" data-style="eyJoaWRlTW9iaWxlIjoxLCJoaWRlVGFibGV0IjoxfQ==" id="le_body_row_15_col_100_el_1"><div class="element"><div class="op-text-block" style="width:300px;text-align: right;padding-top:20px;"><p style="font-size:38px;font-family:&quot;Just Another Hand&quot;, serif;color:#444444;letter-spacing:1px;">Join us Now!</p>
</div></div></div></div><div class="split-half column cols subcol" id="le_body_row_15_col_101"><div class="element-container cf hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet hide-mobile hide-tablet" data-style="eyJoaWRlTW9iaWxlIjoxLCJoaWRlVGFibGV0IjoxfQ==" id="le_body_row_15_col_101_el_1"><div class="element"><div class="arrow-right"><img src="<?php  echo get_template_directory_uri(); ?>/images/arrow-9-1.png" class="arrows" alt="arrow" height="55" width="145"></div></div></div></div><div class="clearcol"></div></div><div class="one-half column cols" id="le_body_row_15_col_2"><div class="element-container cf" data-style="" id="le_body_row_15_col_2_el_1"><div class="element"> <div class="op-text-block" style="width:370px;line-height:22px;margin: 0 auto;text-align:center;"><p style="font-size:18px;line-height:22px;text-align: center;">Enter your first name and email address to join our&nbsp;<strong>FREE ONLINE Summit</strong></p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_15_col_2_el_2"><div class="element"> <div style="height:30px"></div> </div></div><div class="element-container cf" data-style="" id="le_body_row_15_col_2_el_3"><div class="element"> <div class="op-popup cf" data-width="700" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442169878147"><div class="op-popup-button "><div style="text-align:center"><style type="text/css">#btn_1_20cac649d6f2e3a3a9c45911f26ea32a .text {font-size:25px;color:#ffffff;font-weight:bold;text-shadow:#ffbb00 0px 1px 0px;}#btn_1_20cac649d6f2e3a3a9c45911f26ea32a .subtext {text-shadow:#ffbb00 0px 1px 0px;}#btn_1_20cac649d6f2e3a3a9c45911f26ea32a {padding:21px 31px;border-color:#000000;border-width:0px;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;background:#ffa600;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffa600), color-stop(100%, #ffa435));background:-webkit-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-moz-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-ms-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-o-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:linear-gradient(to bottom, #ffa600 0%, #ffa435 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffa600, endColorstr=#ffa435, GradientType=0);box-shadow:none;}#btn_1_20cac649d6f2e3a3a9c45911f26ea32a .gradient {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_20cac649d6f2e3a3a9c45911f26ea32a .shine {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_20cac649d6f2e3a3a9c45911f26ea32a .active {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_20cac649d6f2e3a3a9c45911f26ea32a .hover {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}</style><a href="" id="btn_1_20cac649d6f2e3a3a9c45911f26ea32a" class="css-button style-1"><span class="text">Claim my spot</span><span class="hover"></span><span class="active"></span></a></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:30px;font-weight:bold;color:#ffa600;">Register For Our Free Summit</p>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:18px;font-style:normal;font-weight:300;color:#212121;">Enter your first name and email to join our FREE Summit&nbsp;and claim your complimentary bonus gift</p>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true">
<div id="58d26e5db0f43" class="optin-box optin-box-6" style="margin-right: auto;margin-left: auto;">
    <div class="optin-box-content">
        <form action="https://forms.ontraport.com/v2.4/form_processor.php?" method="post" class="cf op-optin-validation"><div style="display:none"><input name="submit-button" value="" type="hidden"><input name="afft_" value="" type="hidden"><input name="aff_" value="" type="hidden"><input name="sess_" value="" type="hidden"><input name="ref_" value="" type="hidden"><input name="own_" value="" type="hidden"><input name="oprid" value="" type="hidden"><input name="contact_id" value="" type="hidden"><input name="utm_source" value="" type="hidden"><input name="utm_medium" value="" type="hidden"><input name="utm_term" value="" type="hidden"><input name="utm_content" value="" type="hidden"><input name="utm_campaign" value="" type="hidden"><input name="referral_page" value="" type="hidden"><input name="uid" value="p2c11452f184" type="hidden"><input name="redirect_url" value="https://forms.ontraport.com/v2.4/form_processor.php?" type="hidden"><input name="email_field" value="email" type="hidden"></div>            <div class="text-boxes">
          <div class="text-box name"><input required="required" name="firstname" placeholder="Enter your first name" type="text"></div><div class="text-box email"><input required="required" name="email" placeholder="Enter your email address" type="email"></div>            </div>
            <input id="op_optin_nonce" name="op_optin_nonce" value="9af5157843" type="hidden"><input name="_wp_http_referer" value="/" type="hidden">            <div style="text-align:center"><style type="text/css">#btn_1_762fdfff51297e5242d85f72e1f207da .text {font-size:25px;color:#ffffff;font-weight:bold;text-shadow:#ffa600 0px 1px 0px;}#btn_1_762fdfff51297e5242d85f72e1f207da .subtext {text-shadow:#ffa600 0px 1px 0px;}#btn_1_762fdfff51297e5242d85f72e1f207da {padding:21px 21px;border-color:#000000;border-width:0px;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;background:#ffa600;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffa600), color-stop(100%, #ffa435));background:-webkit-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-moz-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-ms-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-o-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:linear-gradient(to bottom, #ffa600 0%, #ffa435 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffa600, endColorstr=#ffa435, GradientType=0);box-shadow:none;}#btn_1_762fdfff51297e5242d85f72e1f207da .gradient {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .shine {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .active {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .hover {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}</style><button type="submit" id="btn_1_762fdfff51297e5242d85f72e1f207da" class="css-button style-1 location_optin_box_style_7"><span class="text">Yes, I want in!</span><span class="hover"></span><span class="active"></span></button></div>                    </form>
    <p class="privacy"><img src="<?php  echo get_template_directory_uri(); ?>/images/privacy.png" alt="privacy" height="15" width="16"> We value your privacy and would never spam you</p>    </div>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:300;color:#212121;">You will also receive our free e-news.<br>
<strong>Your info will never be shared or sold. Ever.</strong></p>
</div></div></div></div> </div></div></div></div></div>
                    <div class="row one-column cf ui-sortable" id="le_body_row_16" data-style="">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_16_col_1"></div></div></div>
                    <div style="background-image:url(&quot;https://happivize.com/wp-content/themes/happivize/images/gradient_bg_1250x200.jpg&quot;);background-repeat:no-repeat; background-size:cover;padding-top:40px;padding-bottom:30px;border-top-width:px;border-top-style:solid;border-top-color:#f5f5f5;border-bottom-width:px;border-bottom-style:solid;border-bottom-color:#f5f5f5;" class="row one-column cf ui-sortable section" id="le_body_row_17" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNmMjY3MjQiLCJiYWNrZ3JvdW5kQ29sb3JFbmQiOiIjZDExYjY4IiwicGFkZGluZ1RvcCI6IjQwIiwicGFkZGluZ0JvdHRvbSI6IjMwIiwiYm9yZGVyVG9wV2lkdGgiOiIiLCJib3JkZXJUb3BDb2xvciI6IiNmNWY1ZjUiLCJib3JkZXJCb3R0b21XaWR0aCI6IiIsImJvcmRlckJvdHRvbUNvbG9yIjoiI2Y1ZjVmNSIsImFkZG9uIjp7fX0=">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_17_col_1"><div class="element-container cf" data-style="" id="le_body_row_17_col_1_el_1"><div class="element"> <h2 style="font-size:45px;font-style:normal;font-weight:300;color:#ffffff;text-align:center;">Join us for This ONLINE SUMMIT</h2> </div></div></div></div></div>
                    <div class="row one-column cf ui-sortable" id="le_body_row_18" data-style="">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_18_col_1"><div class="element-container cf" data-style="" id="le_body_row_18_col_1_el_1"><div class="element"> <h2 style="font-size:35px;color:#444444;text-align:center;">Join us from&nbsp;anywhere in the world.</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_18_col_1_el_2"><div class="element"> <h2 style="font-size:28px;font-style:normal;font-weight:normal;color:#7cc15a;letter-spacing:1px;text-align:center;">The
 festival runs three&nbsp;weeks, and there will be plenty of replay 
opportunities to listen to any speakers you may have missed...<br>
including full replays after the event is over! We want you to have time to connect with each expert!</h2> </div></div></div></div></div>
                    <!--div style="background:#f7f7f7;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #f7f7f7), color-stop(100%, #f7f7f7));background:-webkit-linear-gradient(top, #f7f7f7 0%, #f7f7f7 100%);background:-moz-linear-gradient(top, #f7f7f7 0%, #f7f7f7 100%);background:-ms-linear-gradient(top, #f7f7f7 0%, #f7f7f7 100%);background:-o-linear-gradient(top, #f7f7f7 0%, #f7f7f7 100%);background:linear-gradient(to bottom, #f7f7f7 0%, #f7f7f7 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#f7f7f7, endColorstr=#f7f7f7, GradientType=0);padding-top:40px;padding-bottom:20px;border-top-width:px;border-top-style:solid;border-top-color:;border-bottom-width:px;border-bottom-style:solid;border-bottom-color:;" class="row one-column cf ui-sortable section" id="le_body_row_19" data-style="eyJiYWNrZ3JvdW5kQ29sb3JTdGFydCI6IiNmN2Y3ZjciLCJiYWNrZ3JvdW5kQ29sb3JFbmQiOiIjZjdmN2Y3IiwicGFkZGluZ1RvcCI6IjQwIiwicGFkZGluZ0JvdHRvbSI6IjIwIiwiYm9yZGVyVG9wV2lkdGgiOiIiLCJib3JkZXJUb3BDb2xvciI6IiIsImJvcmRlckJvdHRvbVdpZHRoIjoiIiwiYm9yZGVyQm90dG9tQ29sb3IiOiIiLCJhZGRvbiI6eyJ2aWRlb19iYWNrZ3JvdW5kX3VybF9tcDQiOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX3VybF93ZWJtIjoiIiwidmlkZW9fYmFja2dyb3VuZF91cmxfb2d2IjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2NvbG9yIjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X29wYWNpdHkiOiIwIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2ltYWdlIjoiIn19">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_19_col_1"><div class="element-container cf" data-style="" id="le_body_row_19_col_1_el_1"><div class="element"> <h2 style="font-size:24px;font-weight:bold;text-align:left;">This
 BOUTIQUE event features two speakers a week so you have plenty of time 
to listen to each speaker and is absolutely free.&nbsp;You don’t want to
 miss it!</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_19_col_1_el_2"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p>You’ll
 get insights and practical information you can use in your life right 
away, from our roster of respected visionaries, authors and experts. 
It’s about reconnecting with the love that you already ARE and learning 
to bring its presences into our everyday lives.</p>
</div> </div></div></div></div></div-->
                    <div style="padding-top:50px;padding-bottom:20px;" class="row one-column cf ui-sortable section" id="le_body_row_20" data-style="eyJwYWRkaW5nVG9wIjoiNTAiLCJwYWRkaW5nQm90dG9tIjoiMjAiLCJhZGRvbiI6eyJ2aWRlb19iYWNrZ3JvdW5kX3VybF9tcDQiOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX3VybF93ZWJtIjoiIiwidmlkZW9fYmFja2dyb3VuZF91cmxfb2d2IjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2NvbG9yIjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X29wYWNpdHkiOiIwIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2ltYWdlIjoiIn19">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_20_col_1"><div class="element-container cf" data-style="" id="le_body_row_20_col_1_el_1"><div class="element"> <h2 style="font-size:24px;font-weight:bold;text-align:left;margin-bottom:30px;">What you’ll learn:</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_20_col_1_el_2"><div class="element"> <ul class="feature-block feature-block-style-icon feature-block-with-icon feature-block-two-col cf">
                    <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/445.png" height="49" width="60"></span><h2>Self-Love is NOT Selfish</h2><p style="font-size:16px;"><span style="color: #444444; font-size: 16px; font-family: 'Source Sans Pro', sans-serif;">Many
 people think loving yourself is thinking “too much of yourself”. But 
it’s not! Self-love is humble and all about loving yourself and feeling 
everybody else is EQUAL and deserving of love. </span></p>

                            </div></li>
                     
                    <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/Premium-Services.png" height="46" width="60"></span><h2>Connecting with your Life Purpose</h2><p style="font-size:16px;">When
 you connect with the love you were born with, you will also be able to 
connect with your true life’s purpose -it’s like it unveils your talents
 and gifts.</p>

                            </div></li>
                     
                    <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/Search-Engine-Optimization.png" height="60" width="60"></span><h2>Love Your Body no matter what</h2><p style="font-size:16px;">It’s
 so easy to disparage our body if isn’t perfect by society’s standard – 
learn to love your body no matter what it looks like or how it presents 
itself to the world – so important before you can make any lasting 
changes!</p>

                            </div></li>
                     
                    <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/239.png" height="60" width="60"></span><h2>Love improves all areas of your life</h2><p style="font-size:16px;">Do
 we even know what love really is? We’ve experienced it in many forms. 
Learn its most divine essence and how to connect with it and too 
everyone – you won’t believe how this can change your life!</p>

                            </div></li>
                     
                    <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/270.png" height="60" width="60"></span><h2>Aging doesn't have to be a dirty word!</h2><p style="font-size:16px;">Most
 of us dread all the symptoms of aging and we also feel like we lose 
some of our value – turn that around so that getting older means getting
 better and valuing yourself even more!</p>

                            </div></li>
                     
                    <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/PageRankBadge.png" height="72" width="60"></span><h2>Be the Authentic You</h2><p style="font-size:16px;">We
 spend so much time hiding parts of us from others and from ourselves! 
Learn how to integrate them and love them so that you are the complete 
real you.</p>

                            </div></li>
                     
                        <li><div><span class="feature-block-icon-container"><img class="feature-block-icon" src="<?php  echo get_template_directory_uri(); ?>/images/Untitled-12.png" height="10" width="10"></span><h2>... and much more</h2>
                                </div></li>
                     </ul> </div></div></div></div></div>
                    <div style="background-image:url(http://lovemyselflovemylife.com/wp-content/uploads/2015/09/bg1012-1.jpg);background-repeat:repeat;padding-top:50px;padding-bottom:20px;border-top-color:#e8e8e8;border-bottom-color:#e8e8e8;" class="row one-column cf ui-sortable section" id="le_body_row_21" data-style="eyJiYWNrZ3JvdW5kSW1hZ2UiOiJ1cmwoaHR0cDovL2xvdmVteXNlbGZsb3ZlbXlsaWZlLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxNS8wOS9iZzEwMTItMS5qcGcpIiwiYmFja2dyb3VuZFBvc2l0aW9uIjoidGlsZSIsInBhZGRpbmdUb3AiOiI1MCIsInBhZGRpbmdCb3R0b20iOiIyMCIsImJvcmRlckNvbG9yIjoiI2U4ZThlOCIsImFkZG9uIjp7fX0=">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_21_col_1"><div class="element-container cf" data-style="" id="le_body_row_21_col_1_el_1"><div class="element"> <h2 style="font-size:24px;font-weight:bold;text-align:left;margin-bottom:30px;">This Online Summit is for you if:</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_21_col_1_el_2"><div class="element"> <ul class="bullet-list 1"><li style="background-image:url(&quot;https://happivize.com/wp-content/themes/happivize/images/star.png&quot;);background-repeat:no-repeat;">You know self-love is important but have a hard time loving yourself consistently</li><li style="background-image:url(&quot;https://happivize.com/wp-content/themes/happivize/images/star.png&quot;);background-repeat:no-repeat;">You beat yourself up for every little mistake you make</li><li style="background-image:url(&quot;https://happivize.com/wp-content/themes/happivize/images/star.png&quot;);background-repeat:no-repeat;">You constantly compare yourself to others and feel they are better than you</li><li style="background-image:url(&quot;https://happivize.com/wp-content/themes/happivize/images/star.png&quot;);background-repeat:no-repeat;">You have the feeling that you just aren't "enough"</li><li style="background-image:url(&quot;https://happivize.com/wp-content/themes/happivize/images/star.png&quot;);background-repeat:no-repeat;">You KNOW that it's possible, are open to new ideas, and WANT to learn to love and accept yourself</li></ul> </div></div></div></div></div>
                    <div class="row one-column cf ui-sortable" id="le_body_row_22" data-style="">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_22_col_1"><div class="element-container cf" data-style="" id="le_body_row_22_col_1_el_1"><div class="element"> 
<div id="796829d32f8bac341ba9272c917f8344" class="feature-box-creator feature-box-creator-style-1" style=" border: 1px #000 solid; border-color: #f26724; border-width: 2px; border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; width: 700px; background-color: #ffffff; background: #ffffff;background: -moz-linear-gradient(top, #ffffff 0%, #ffffff 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#ffffff));background: -webkit-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -o-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: -ms-linear-gradient(top, #ffffff 0%,#ffffff 100%);background: linear-gradient(top,  0%, 100%));filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ffffff',GradientType=0 );">
    <div class="feature-box-content cf"><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;text-align: center;"><strong>I found myself saying in my mind “I love myself. I love my life!”</strong></p>
</div>
</div><div class="row element-container cf "><div class="op-text-block" style="width:100%;text-align: left;"><p style="font-size:18px;font-style:italic;color:#000000;"><img class=" size-full wp-image-1273 alignleft" src="<?php  echo get_template_directory_uri(); ?>/images/quotation-marks-111.jpg" alt="quotation-marks-111" height="48" width="50"></p>
<p style="font-size:18px;font-style:italic;color:#000000;"><em>I was out
 and about the other day, I was feeling pretty good and I found myself 
saying in my mind “I love myself.&nbsp; I love my life!”&nbsp; As I 
heard myself saying that, I thought OH I really like that!&nbsp; (This 
is not the typical self-talk I have in my head.)&nbsp; I felt really 
good, rejuvenated and empowered as I said those words to myself.&nbsp; I
 then became inquisitive as to where I got that beautiful thought? Then 
it came to me . . . from you!&nbsp; Thank you!</em></p>
<p style="font-size:18px;font-style:italic;color:#000000;">- <em><cite>Tammy, California</cite></em></p>
</div>
</div></div>
</div> </div></div></div></div></div>
                    <div style="padding-bottom:0px;" class="row one-column cf ui-sortable section" id="le_body_row_23" data-style="eyJwYWRkaW5nQm90dG9tIjoiMCIsImFkZG9uIjp7InZpZGVvX2JhY2tncm91bmRfdXJsX21wNCI6IiIsInZpZGVvX2JhY2tncm91bmRfdXJsX3dlYm0iOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX3VybF9vZ3YiOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX292ZXJsYXlfY29sb3IiOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX292ZXJsYXlfb3BhY2l0eSI6IjAiLCJ2aWRlb19iYWNrZ3JvdW5kX292ZXJsYXlfaW1hZ2UiOiIifX0=">
                        <div class="fixed-width"><div class="one-column column cols" id="le_body_row_23_col_1"><div class="element-container cf" data-style="" id="le_body_row_23_col_1_el_1"><div class="element"> <h2 style="color:#ffa600;text-align:center;">Experience some major breakthroughs and feel good moments!</h2> </div></div><div class="element-container cf" data-style="" id="le_body_row_23_col_1_el_2"><div class="element"> <div class="op-text-block" style="width:600px;line-height:22px;margin: 0 auto;text-align:center;"><p style="font-size:18px;line-height:22px;text-align: center;">Enter your first name and email address to join our&nbsp;FREE Online&nbsp;Summit and <span style="color: 41a4d1;"><strong>claim your complimentary bonus gift</strong></span></p>
</div> </div></div></div></div></div>
                    <div style="" class="row four-columns cf ui-sortable section" id="le_body_row_24" data-style="eyJhZGRvbiI6eyJ2aWRlb19iYWNrZ3JvdW5kX3VybF9tcDQiOiIiLCJ2aWRlb19iYWNrZ3JvdW5kX3VybF93ZWJtIjoiIiwidmlkZW9fYmFja2dyb3VuZF91cmxfb2d2IjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2NvbG9yIjoiIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X29wYWNpdHkiOiIwIiwidmlkZW9fYmFja2dyb3VuZF9vdmVybGF5X2ltYWdlIjoiIn19">
                        <div class="fixed-width"><div class="one-fourth column cols narrow" id="le_body_row_24_col_1"><div class="element-container cf hide-mobile hide-tablet" data-style="eyJoaWRlTW9iaWxlIjoxLCJoaWRlVGFibGV0IjoxfQ==" id="le_body_row_24_col_1_el_1"><div class="element">
                <div class="image-caption" style="width:145px;margin-top:0px;margin-bottom:px;margin-right:auto;margin-left:auto;"><img alt="" src="<?php  echo get_template_directory_uri(); ?>/images/arrow-point-right.png" class="full-width" border="0" height="79" width="145"></div>
            </div></div></div><div class="two-fourths column cols" id="le_body_row_24_col_2"><div class="element-container cf" data-style="" id="le_body_row_24_col_2_el_1"><div class="element"> <div class="op-popup cf" data-width="700" data-open-effect="fade" data-close-effect="fade" data-open-speed="normal" data-close-speed="normal" data-border-color="#ffffff" data-border-size="15" data-padding-top="20" data-padding-bottom="20" data-padding-left="30" data-padding-right="30" data-exit-intent="N" data-trigger-time="0" data-trigger-dontshow="0" data-dont-show-on-tablet="N" data-dont-show-on-mobile="N" data-popup-id="op_popup_id_1442169878147"><div class="op-popup-button "><div style="text-align:center"><style type="text/css">#btn_1_c5f917a3a32f25ad4d6e31f4467e689f .text {font-size:25px;color:#ffffff;font-weight:bold;text-shadow:#ffbb00 0px 1px 0px;}#btn_1_c5f917a3a32f25ad4d6e31f4467e689f .subtext {text-shadow:#ffbb00 0px 1px 0px;}#btn_1_c5f917a3a32f25ad4d6e31f4467e689f {padding:21px 31px;border-color:#000000;border-width:0px;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;background:#ffa600;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffa600), color-stop(100%, #ffa435));background:-webkit-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-moz-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-ms-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-o-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:linear-gradient(to bottom, #ffa600 0%, #ffa435 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffa600, endColorstr=#ffa435, GradientType=0);box-shadow:none;}#btn_1_c5f917a3a32f25ad4d6e31f4467e689f .gradient {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_c5f917a3a32f25ad4d6e31f4467e689f .shine {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_c5f917a3a32f25ad4d6e31f4467e689f .active {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_c5f917a3a32f25ad4d6e31f4467e689f .hover {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}</style><a href="" id="btn_1_c5f917a3a32f25ad4d6e31f4467e689f" class="css-button style-1"><span class="text">I want to love myself!</span><span class="hover"></span><span class="active"></span></a></div></div><div class="op-popup-content"><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:30px;font-weight:bold;color:#ffa600;">Register For Our Free Summit</p>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:18px;font-style:normal;font-weight:300;color:#212121;">Enter your first name and email to join out FREE Summit&nbsp;and claim your complimentary bonus gift</p>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true">
<div id="58d26e5db0f43" class="optin-box optin-box-6" style="margin-right: auto;margin-left: auto;">
    <div class="optin-box-content">
        <form action="https://forms.ontraport.com/v2.4/form_processor.php?" method="post" class="cf op-optin-validation"><div style="display:none"><input name="submit-button" value="" type="hidden"><input name="afft_" value="" type="hidden"><input name="aff_" value="" type="hidden"><input name="sess_" value="" type="hidden"><input name="ref_" value="" type="hidden"><input name="own_" value="" type="hidden"><input name="oprid" value="" type="hidden"><input name="contact_id" value="" type="hidden"><input name="utm_source" value="" type="hidden"><input name="utm_medium" value="" type="hidden"><input name="utm_term" value="" type="hidden"><input name="utm_content" value="" type="hidden"><input name="utm_campaign" value="" type="hidden"><input name="referral_page" value="" type="hidden"><input name="uid" value="p2c11452f184" type="hidden"><input name="redirect_url" value="https://forms.ontraport.com/v2.4/form_processor.php?" type="hidden"><input name="email_field" value="email" type="hidden"></div>            <div class="text-boxes">
          <div class="text-box name"><input required="required" name="firstname" placeholder="Enter your first name" type="text"></div><div class="text-box email"><input required="required" name="email" placeholder="Enter your email address" type="email"></div>            </div>
            <input id="op_optin_nonce" name="op_optin_nonce" value="9af5157843" type="hidden"><input name="_wp_http_referer" value="/" type="hidden">            <div style="text-align:center"><style type="text/css">#btn_1_762fdfff51297e5242d85f72e1f207da .text {font-size:25px;color:#ffffff;font-weight:bold;text-shadow:#ffa600 0px 1px 0px;}#btn_1_762fdfff51297e5242d85f72e1f207da .subtext {text-shadow:#ffa600 0px 1px 0px;}#btn_1_762fdfff51297e5242d85f72e1f207da {padding:21px 21px;border-color:#000000;border-width:0px;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;background:#ffa600;background:-webkit-gradient(linear, left top, left bottom, color-stop(0%, #ffa600), color-stop(100%, #ffa435));background:-webkit-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-moz-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-ms-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:-o-linear-gradient(top, #ffa600 0%, #ffa435 100%);background:linear-gradient(to bottom, #ffa600 0%, #ffa435 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#ffa600, endColorstr=#ffa435, GradientType=0);box-shadow:none;}#btn_1_762fdfff51297e5242d85f72e1f207da .gradient {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .shine {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .active {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#btn_1_762fdfff51297e5242d85f72e1f207da .hover {-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}</style><button type="submit" id="btn_1_762fdfff51297e5242d85f72e1f207da" class="css-button style-1 location_optin_box_style_7"><span class="text">Yes, I want in!</span><span class="hover"></span><span class="active"></span></button></div>                    </form>
    <p class="privacy"><img src="<?php  echo get_template_directory_uri(); ?>/images/privacy.png" alt="privacy" height="15" width="16"> We value your privacy and would never spam you</p>    </div>
</div></div><div class="element-container op-popup-element-container " data-popup-child="true"><div class="op-text-block" style="width:100%;margin: 0 auto;text-align:center;"><p style="font-size:14px;font-style:normal;font-weight:300;color:#212121;">You will also receive our free e-news.<br>
<strong>Your info will never be shared or sold. Ever.</strong></p>
</div></div></div></div> </div></div></div><div class="one-fourth column cols narrow" id="le_body_row_24_col_3"><div class="element-container cf hide-mobile hide-tablet" data-style="eyJoaWRlTW9iaWxlIjoxLCJoaWRlVGFibGV0IjoxfQ==" id="le_body_row_24_col_3_el_1"><div class="element">
                <div class="image-caption" style="width:145px;margin-top:0px;margin-bottom:px;margin-right:px;margin-left:px;float: left;"><img alt="" src="<?php  echo get_template_directory_uri(); ?>/images/arrow-point-left.png" class="full-width" border="0" height="79" width="145"></div>
            </div></div></div></div></div></div>   
            </div>
<?php get_footer(); ?>
