<?php
if (!class_exists('PopupAllyProFluidTemplateFullWidthClickOpen')) {
	class PopupAllyProFluidTemplateFullWidthClickOpen extends PopupAllyProFluidTemplate {
		public function __construct() {
			parent::__construct();
			$this->uid = 'fluid_nwutsf';
			$this->template_name = 'Full Width Click Open';

			$this->default_values = array($this->uid => array(
"checked-customization-opened" => "false",
"checked-hide-overlay" => "false",
"overlay-color" => "#505050",
"overlay-opacity" => "0.5",
"overlay-color-rgba" => "80,80,80,0.5",
"checked-disable-overlay-close" => "false",
"selected-responsive" => "0",
'element-order' => array('1', '2'),
"elements" => array(
	"1" => array(
		"type" => "text",
		"title" => "Headline",
		"text" => "Send me the FREE eBook",
		"select-click-action" => "popup",
		"click-link" => "",
		"click-new-link" => "",
		"click-popup-id" => "",
		),
	"2" => array(
		"type" => "text",
		"title" => "Link Button",
		"text" => "Sign up!",
		"select-click-action" => "none",
		"click-link" => "",
		"click-new-link" => "",
		"click-popup-id" => "",
		),
	),
"responsive" => array(
	"0" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "1024",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "false",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "false",
		"background-image-url" => "",
		"checked-background-image-inherit" => "false",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "false",
		"label" => "Desktop",
		"width" => "900",
		"height" => "40",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "false",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "660px",
					"height" => "auto",
					"left" => "40px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "20",
					"font-weight" => "700",
					"line-height" => "40",
					'color' => '#111111',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "120px",
					"height" => "26px",
					"top" => "7px",
					"left" => "740px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					"line-height" => "26",
					),
				),
			),
		),
	"1" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "960",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "true",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "true",
		"background-image-url" => "",
		"checked-background-image-inherit" => "true",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "true",
		"label" => "Tablet",
		"width" => "640",
		"height" => "40",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "true",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "510px",
					"height" => "auto",
					"left" => "10px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "20",
					"font-weight" => "700",
					"line-height" => "40",
					'color' => '#111111',
					),
				"inherit" => array(
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					'color' => 'true',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "85px",
					"height" => "26px",
					"top" => "7px",
					"left" => "540px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					"line-height" => "26",
					),
				"inherit" => array(
					"background-color" => "true",
					"color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					"border-radius" => "true",
					),
				),
			),
		),
	"2" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "640",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "true",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "true",
		"background-image-url" => "",
		"checked-background-image-inherit" => "true",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "true",
		"label" => "Large Phone",
		"width" => "400",
		"height" => "40",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "true",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "280px",
					"height" => "auto",
					"left" => "10px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "20",
					"font-weight" => "700",
					"line-height" => "40",
					'color' => '#111111',
					),
				"inherit" => array(
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					'color' => 'true',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "80px",
					"height" => "26px",
					"top" => "7px",
					"left" => "300px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					"line-height" => "26",
					),
				"inherit" => array(
					"background-color" => "true",
					"color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					"border-radius" => "true",
					),
				),
			),
		),
	"3" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "480",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "true",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "true",
		"background-image-url" => "",
		"checked-background-image-inherit" => "true",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "true",
		"label" => "Small Phone",
		"width" => "280",
		"height" => "40",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "true",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"css" => array(
					"width" => "190px",
					"height" => "auto",
					"left" => "10px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "16",
					"font-weight" => "700",
					"line-height" => "40",
					'color' => '#111111',
					),
				"inherit" => array(
					"font-family" => "true",
					"font-weight" => "true",
					'color' => 'true',
					),
				),
			"2" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "60px",
					"height" => "26px",
					"top" => "7px",
					"left" => "215px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "14",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					"line-height" => "26",
					),
				"inherit" => array(
					"background-color" => "true",
					"color" => "true",
					"font-family" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					"border-radius" => "true",
					),
				),
			),
		),
	),
)
				);
		} /* end __construct */
	}
	
	PopupAllyProFluidTemplate::add_template(new PopupAllyProFluidTemplateFullWidthClickOpen());
}