<?php
if (!class_exists('PopupAllyProFluidTemplateFullWidthOptin')) {
	class PopupAllyProFluidTemplateFullWidthOptin extends PopupAllyProFluidTemplate {
		public function __construct() {
			parent::__construct();
			$this->uid = 'fluid_wdsmhs';
			$this->template_name = 'Full Width Opt-in';

			$this->default_values = array($this->uid => array(
"checked-customization-opened" => "false",
"checked-hide-overlay" => "false",
"overlay-color" => "#505050",
"overlay-opacity" => "0.5",
"overlay-color-rgba" => "80,80,80,0.5",
"checked-disable-overlay-close" => "false",
"selected-responsive" => "0",
'element-order' => array('1', '2', '3', '4'),
"elements" => array(
	"1" => array(
		"type" => "text",
		"title" => "Headline",
		"text" => "Send me the FREE eBook",
		"select-click-action" => "none",
		"click-link" => "",
		"click-new-link" => "",
		"click-popup-id" => "",
		),
	"2" => array(
		"type" => "input",
		"title" => "Name Input",
		"placeholder" => "Name",
		"multi-placeholder" => "Input",
		"select-input-type" => "single",
		"checked-is-email" => "false",
		"form-select-single-field" => "",
		"checked-single-required" => "true",
		"single-field-label" => "Input",
		"form-select-multi-field" => "",
		"checked-multi-required" => "true",
		"multi-field-label" => "Input",
		"form-select-dropdown-field" => "",
		"checked-dropdown-required" => "false",
		"dropdown-field-label" => "Input",
		"dropdown-options" => "",
		"form-select-checkbox-field" => "",
		"select-checkbox-default-value" => "unchecked",
		"checkbox-field-label" => "Input",
		),
	"3" => array(
		"type" => "input",
		"title" => "Email Input",
		"placeholder" => "Email",
		"multi-placeholder" => "Input",
		"select-input-type" => "single",
		"checked-is-email" => "true",
		"form-select-single-field" => "",
		"checked-single-required" => "true",
		"single-field-label" => "Input",
		"form-select-multi-field" => "",
		"checked-multi-required" => "true",
		"multi-field-label" => "Input",
		"form-select-dropdown-field" => "",
		"checked-dropdown-required" => "false",
		"dropdown-field-label" => "Input",
		"dropdown-options" => "",
		"form-select-checkbox-field" => "",
		"select-checkbox-default-value" => "unchecked",
		"checkbox-field-label" => "Input",
		),
	"4" => array(
		"type" => "submit",
		"title" => "Submit Button",
		"text" => "Sign up!",
		),
	),
"responsive" => array(
	"0" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "1024",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "false",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "false",
		"background-image-url" => "",
		"checked-background-image-inherit" => "false",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "false",
		"label" => "Desktop",
		"width" => "900",
		"height" => "40",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "false",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "280px",
					"height" => "auto",
					"left" => "40px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "20",
					"font-weight" => "700",
					"text-align" => "left",
					"line-height" => "40",
					'color' => '#111111',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "200px",
					"height" => "26px",
					"top" => "7px",
					"left" => "300px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				),
			"3" => array(
				"css" => array(
					"width" => "200px",
					"height" => "26px",
					"top" => "7px",
					"left" => "520px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				),
			"4" => array(
				"css" => array(
					"width" => "120px",
					"height" => "26px",
					"top" => "7px",
					"left" => "740px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					),
				),
			),
		),
	"1" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "960",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "true",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "true",
		"background-image-url" => "",
		"checked-background-image-inherit" => "true",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "true",
		"label" => "Tablet",
		"width" => "640",
		"height" => "40",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "true",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "220px",
					"height" => "auto",
					"left" => "10px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "18",
					"font-weight" => "700",
					"text-align" => "left",
					"line-height" => "40",
					'color' => '#111111',
					),
				"inherit" => array(
					"font-family" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					'color' => 'true',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "142px",
					"height" => "26px",
					"top" => "7px",
					"left" => "230px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				"inherit" => array(
					"background-color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"border-radius" => "true",
					'color' => 'true',
					),
				),
			"3" => array(
				"css" => array(
					"width" => "142px",
					"height" => "26px",
					"top" => "7px",
					"left" => "380px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				"inherit" => array(
					"background-color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"border-radius" => "true",
					'color' => 'true',
					),
				),
			"4" => array(
				"css" => array(
					"width" => "85px",
					"height" => "26px",
					"top" => "7px",
					"left" => "540px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					),
				"inherit" => array(
					"background-color" => "true",
					"color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					"border-radius" => "true",
					),
				),
			),
		),
	"2" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "640",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "true",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "true",
		"background-image-url" => "",
		"checked-background-image-inherit" => "true",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "true",
		"label" => "Large Phone",
		"width" => "400",
		"height" => "60",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "true",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "100%",
					"height" => "auto",
					"left" => "0px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "20",
					"font-weight" => "700",
					"text-align" => "center",
					"line-height" => "30",
					'color' => '#111111',
					),
				"inherit" => array(
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					'color' => 'true',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "130px",
					"height" => "26px",
					"top" => "30px",
					"left" => "20px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				"inherit" => array(
					"background-color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"border-radius" => "true",
					'color' => 'true',
					),
				),
			"3" => array(
				"css" => array(
					"width" => "130px",
					"height" => "26px",
					"top" => "30px",
					"left" => "160px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				"inherit" => array(
					"background-color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"border-radius" => "true",
					'color' => 'true',
					),
				),
			"4" => array(
				"css" => array(
					"width" => "80px",
					"height" => "26px",
					"top" => "30px",
					"left" => "300px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					),
				"inherit" => array(
					"background-color" => "true",
					"color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					"border-radius" => "true",
					),
				),
			),
		),
	"3" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "480",
		"select-border-box-shadow" => "0 5px 10px rgba(0,0,0,0.5)",
		"checked-border-box-shadow-inherit" => "true",
		"background-color" => "#E34A63",
		"checked-background-color-inherit" => "true",
		"background-image-url" => "",
		"checked-background-image-inherit" => "true",
		"checked-full-width" => "true",
		"checked-full-width-inherit" => "true",
		"label" => "Small Phone",
		"width" => "280",
		"height" => "60",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "true",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"css" => array(
					"width" => "100%",
					"height" => "auto",
					"left" => "0px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "20",
					"font-weight" => "700",
					"text-align" => "center",
					"line-height" => "30",
					'color' => '#111111',
					),
				"inherit" => array(
					"font-family" => "true",
					"font-size" => "true",
					"font-weight" => "true",
					'color' => 'true',
					),
				),
			"2" => array(
				"css" => array(
					"width" => "100px",
					"height" => "26px",
					"top" => "30px",
					"left" => "5px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				"inherit" => array(
					"background-color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"border-radius" => "true",
					'color' => 'true',
					),
				),
			"3" => array(
				"css" => array(
					"width" => "100px",
					"height" => "26px",
					"top" => "30px",
					"left" => "110px",
					"background-color" => "#F6F6F6",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "16",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					'color' => '#444444',
					),
				"inherit" => array(
					"background-color" => "true",
					"font-family" => "true",
					"font-size" => "true",
					"border-radius" => "true",
					'color' => 'true',
					),
				),
			"4" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "60px",
					"height" => "26px",
					"top" => "30px",
					"left" => "215px",
					"background-color" => "#81D742",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "14",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					),
				"inherit" => array(
					"background-color" => "true",
					"color" => "true",
					"font-family" => "true",
					"font-weight" => "true",
					"text-align" => "true",
					"border-radius" => "true",
					),
				),
			),
		),
	),
)
				);
		} /* end __construct */
	}
	
	PopupAllyProFluidTemplate::add_template(new PopupAllyProFluidTemplateFullWidthOptin());
}