<?php
if (!class_exists('PopupAllyProFluidTemplateSidebarSidekick')) {
	class PopupAllyProFluidTemplateSidebarSidekick extends PopupAllyProFluidTemplate {
		public function __construct() {
			parent::__construct();
			$this->uid = 'fluid_kisjds';
			$this->template_name = 'Sidebar Sidekick';

			$this->default_values = array($this->uid => array(
"checked-customization-opened" => "false",
"checked-hide-overlay" => "false",
"overlay-color" => "#505050",
"overlay-opacity" => "0.5",
"overlay-color-rgba" => "80,80,80,0.5",
"checked-disable-overlay-close" => "false",
"selected-responsive" => "0",
'element-order' => array('1', '2', '3', '4'),
"elements" => array(
	"1" => array(
		"type" => "text",
		"title" => "Headline",
		"text" => "Yes, I want the secret keys...",
		"select-click-action" => "none",
		"click-link" => "",
		"click-new-link" => "",
		"click-popup-id" => "",
		),
	"2" => array(
		"type" => "input",
		"title" => "Name Input",
		"placeholder" => "Name",
		"multi-placeholder" => "Input",
		"select-input-type" => "single",
		"checked-is-email" => "false",
		"form-select-single-field" => "",
		"checked-single-required" => "true",
		"single-field-label" => "Input",
		"form-select-multi-field" => "",
		"checked-multi-required" => "true",
		"multi-field-label" => "Input",
		"form-select-dropdown-field" => "",
		"checked-dropdown-required" => "false",
		"dropdown-field-label" => "Input",
		"dropdown-options" => "",
		"form-select-checkbox-field" => "",
		"select-checkbox-default-value" => "unchecked",
		"checkbox-field-label" => "Input",
		),
	"3" => array(
		"type" => "input",
		"title" => "Email Input",
		"placeholder" => "Email",
		"multi-placeholder" => "Input",
		"select-input-type" => "single",
		"checked-is-email" => "true",
		"form-select-single-field" => "",
		"checked-single-required" => "true",
		"single-field-label" => "Input",
		"form-select-multi-field" => "",
		"checked-multi-required" => "true",
		"multi-field-label" => "Input",
		"form-select-dropdown-field" => "",
		"checked-dropdown-required" => "false",
		"dropdown-field-label" => "Input",
		"dropdown-options" => "",
		"form-select-checkbox-field" => "",
		"select-checkbox-default-value" => "unchecked",
		"checkbox-field-label" => "Input",
		),
	"4" => array(
		"type" => "submit",
		"title" => "Submit Button",
		"text" => "Get The Keys",
		),
	),
"responsive" => array(
	"0" => array(
		"checked-popup-customization-opened" => "false",
		"checked-preview-no-step-aside" => "false",
		"preview-window-background-color" => "#FFFFFF",
		"responsive-breakpoint" => "1024",
		"select-border-box-shadow" => "none",
		"checked-border-box-shadow-inherit" => "false",
		"background-color" => "#FEF9B2",
		"checked-background-color-inherit" => "false",
		"background-image-url" => "",
		"checked-background-image-inherit" => "false",
		"checked-full-width" => "false",
		"checked-full-width-inherit" => "false",
		"label" => "Desktop",
		"width" => "200",
		"height" => "220",
		"select-popup-location" => "center",
		"checked-popup-location-inherit" => "false",
		"select-popup-vertical-selection" => "top",
		"select-popup-horizontal-selection" => "left",
		"popup-top" => "50%",
		"popup-left" => "50%",
		"popup-bottom" => "50%",
		"popup-right" => "50%",
		"checked-auto-adjust" => "false",
		"elements" => array(
			"1" => array(
				"css" => array(
					"width" => "100%",
					"height" => "auto",
					"top" => "20px",
					"font-family" => "\"Palatino Linotype\", \"Book Antiqua\", Palatino, serif",
					"font-size" => "24",
					"font-weight" => "700",
					"text-align" => "center",
					"line-height" => "28",
					"color" => "#7D850F",
					),
				),
			"2" => array(
				"css" => array(
					"width" => "90%",
					"height" => "30px",
					"top" => "100px",
					"left" => "5%",
					"background-color" => "#FEFEFE",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "14",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					),
				),
			"3" => array(
				"css" => array(
					"width" => "90%",
					"height" => "30px",
					"top" => "140px",
					"left" => "5%",
					"background-color" => "#FEFEFE",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "14",
					"padding-top" => "5",
					"padding-right" => "5",
					"padding-bottom" => "5",
					"padding-left" => "5",
					"border-radius" => "5",
					),
				),
			"4" => array(
				"checked-customization-opened" => "false",
				"css" => array(
					"width" => "90%",
					"height" => "30px",
					"top" => "180px",
					"left" => "5%",
					"background-color" => "#162466",
					"color" => "#FFFFFF",
					"font-family" => "Arial, Helvetica, sans-serif",
					"font-size" => "20",
					"font-weight" => "700",
					"text-align" => "center",
					"border-radius" => "5",
					),
				),
			),
		),
	),
)
			);
		} /* end __construct */
	}
	
	PopupAllyProFluidTemplate::add_template(new PopupAllyProFluidTemplateSidebarSidekick());
}